ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "hasPackaging" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "packagingPlateId" INTEGER;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "packagingQuantity" INTEGER;
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "packagingCuttingTimePerPoseSeconds" INTEGER NOT NULL DEFAULT 20;
