-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "batTimeMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "beTimeMinutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hasBE" BOOLEAN NOT NULL DEFAULT false;
