export const QUOTE_DEFAULTS = {
  client: '' as string,
  printMode: 'production' as 'production' | 'quality',
  isRectoVerso: false as boolean,
  inkMlVerso: 0 as number,
  hasVarnish: false as boolean,
  hasFlatColor: false as boolean,
  varnishSurfacePercent: 0 as number,
  flatColorSurfacePercent: 0 as number,
  cuttingTimePerPoseSeconds: 0 as number,
  assemblyTimePerPieceSeconds: 0 as number,
  packTimePerPieceSeconds: 0 as number,
  hasAssemblyNotice: false as boolean,
  hasPackaging: false as boolean,
  packagingCuttingTimePerPoseSeconds: 20 as number,
  printSetupType: 'none' as 'none' | 'standard' | 'complexe',
  cuttingSetupType: 'none' as 'none' | 'standard' | 'complexe',
  hasImpression: true as boolean,
  hasFaconnage: true as boolean,
  hasConditionnement: true as boolean,
  hasAccessoires: false as boolean,
  isMultiProduct: false as boolean,
  hasDossierFee: false as boolean,
  // ── Bureau d'études ──
  hasBE: false as boolean,
  beTimeMinutes: 0 as number,
  batTimeMinutes: 0 as number,
  // ── Marges internes ──
  showMargeCommerciale: false as boolean,
  showMargeSopano: false as boolean,
  // ── Prix négocié matière ──
  plateCostOverride: null as number | null,
  // ── Transport ──
  transportDeliveries: [] as import('@/types/calculator').TransportDeliveryForm[],
}