export const QUOTE_DEFAULTS = {
  client: '' as string,
  contactName: '' as string,
  printMode: 'production' as 'production' | 'quality',
  isRectoVerso: false as boolean,
  inkMlVerso: 0 as number,
  hasVarnish: false as boolean,
  hasFlatColor: false as boolean,
  varnishSurfacePercent: 0 as number,
  varnishMlPerPlate: 0 as number,
  flatColorSurfacePercent: 0 as number,
  cuttingTimePerPoseSeconds: 0 as number,
  assemblyTimePerPieceSeconds: 0 as number,
  packTimePerPieceSeconds: 0 as number,
  hasAssemblyNotice: false as boolean,
  hasPoseEtiquette: false as boolean,
  hasPackaging: false as boolean,
  packagingBoxType: 'etui' as 'etui' | 'caisse' | 'plaque_rainee',
  packagingMaterialType: 'BC' as 'B' | 'EB' | 'C' | 'BC',
  packagingExternalSize: null as 'petit' | 'moyen' | 'grand' | null,
  packagingProductLength: 0 as number,
  packagingProductWidth: 0 as number,
  packagingProductHeight: 0 as number,
  packagingProductThickness: 0 as number,
  packagingCuttingTimePerPoseSeconds: 20 as number,
  printSetupType: 'none' as 'none' | 'standard' | 'complexe',
  cuttingSetupType: 'none' as 'none' | 'standard' | 'complexe',
  hasImpression: true as boolean,
  hasFaconnage: true as boolean,
  hasConditionnement: true as boolean,
  hasAccessoires: false as boolean,
  accessoriesMargePercent: 0 as number,
  packagingMargePercent: 0 as number,
  isMultiProduct: false as boolean,
  plvQuantity: null as number | null,
  hasDossierFee: false as boolean,
  cumulerTemps: false as boolean,
  // ── Bureau d'études ──
  hasBE: false as boolean,
  beTimeMinutes: 0 as number,
  batTimeMinutes: 0 as number,
  // ── Marges internes ──
  showMargeCommerciale: false as boolean,
  showMargeSopano: false as boolean,
  // ── Imposition ──
  bordABord: false as boolean,
  itemsPerPlateOverride: null as number | null,
  // ── Temps machine impression (override manuel) ──
  machineTimeMinOverride: null as number | null,
  // ── Prix négocié matière ──
  plateCostOverride: null as number | null,
  // ── Matière personnalisée (non enregistrée en DB) ──
  customPlate: null as { name: string; width: number; height: number; cost: number } | null,
  // ── Prix emballage (override manuel) ──
  packagingUnitPriceOverride: null as number | null,
  // ── Transport ──
  transportDeliveries: [] as import('@/types/calculator').TransportDeliveryForm[],
}