export const SAMPLE_QUOTE = {
  id: 42,
  reference: 'DEV-2026-042',
  client: 'Carrefour France',
  createdAt: new Date('2026-05-12'),
  quantity: 500,
  plvQuantity: 500,
  flatWidth: 450,
  flatHeight: 1100,
  totalCost: 4820.50,
  transportTotal: 145.00,
  hasAmalgame: true,
  amalgameRuns: [
    {
      name: 'Amalgame',
      hasImpression: true,
      platesCount: 63,
      machineTimeMinOverride: 47.25,
      cuttingTimePerPoseSeconds: 12,
      inkMlPerPlate: 22,
      isRectoVerso: true,
      rectoVersoType: 'identical',
      plate: { name: 'PVC 3mm', width: 600, height: 1200 },
      items: [
        { name: 'Totem Rectangle', flatWidth: 450, flatHeight: 1100, countPerPlate: 4, quantityPerUnit: 1 },
        { name: 'Pop-up comptoir', flatWidth: 320, flatHeight: 480, countPerPlate: 8, quantityPerUnit: 1 },
        { name: 'Etrier de rayon', flatWidth: 280, flatHeight: 200, countPerPlate: 20, quantityPerUnit: 1 },
      ],
    },
  ],
  transportDeliveries: [
    { transportMode: 'PACK30', department: '75', weightKg: 18, units: 4, optionsHT: 0, basePriceHT: 145, totalHT: 145 },
  ],
  cuttingTimePerPoseSeconds: 12,
  assemblyTimePerPieceSeconds: 45 as number | null,
  packTimePerPieceSeconds: 30 as number | null,
  hasFaconnage: true,
  hasConditionnement: true,
  hasImpression: true,
  isRectoVerso: true,
  rectoVersoType: 'identical',
  hasVarnish: true,
  hasFlatColor: false,
  hasAssemblyNotice: false,
  isMultiProduct: true,
  inkMlPerPlate: 22,
  platesCount: 63,
  itemsPerPlate: 4,
  hasPackaging: true,
  packagingQuantity: 250,
  packagingPlate: null,
  packagingBoxType: 'etui',
  packagingMaterialType: 'BC',
  packagingExternalSize: null,
  packagingUnitPriceOverride: 3.20,
  study: { number: '2026-042' },
  productType: { name: 'Totem Rectangle' },
  plate: { name: 'PVC 3mm', cost: 28.50, width: 600, height: 1200 },
  accessories: [
    { accessory: { name: 'Pied chromé 50cm', price: 12.50 }, quantity: 500 },
  ],
  products: [
    {
      id: 1, productTypeName: 'Totem Rectangle',
      flatWidth: 450, flatHeight: 1100, quantity: 500,
      plate: { name: 'PVC 3mm', width: 600, height: 1200 },
      platesCount: 63, itemsPerPlate: 4,
      isRectoVerso: true, rectoVersoType: 'identical',
      hasVarnish: true, hasFlatColor: false, hasImpression: true,
      inkMlPerPlate: 22, cuttingTimePerPoseSeconds: 12,
      amalgameGroupIndex: 0, countPerPlateInGroup: 4,
    },
    {
      id: 2, productTypeName: 'Pop-up comptoir',
      flatWidth: 320, flatHeight: 480, quantity: 500,
      plate: { name: 'PVC 3mm', width: 600, height: 1200 },
      platesCount: null, itemsPerPlate: null,
      isRectoVerso: false, rectoVersoType: null,
      hasVarnish: false, hasFlatColor: false, hasImpression: true,
      inkMlPerPlate: 22, cuttingTimePerPoseSeconds: 12,
      amalgameGroupIndex: 0, countPerPlateInGroup: 8,
    },
    {
      id: 3, productTypeName: 'Etrier de rayon',
      flatWidth: 280, flatHeight: 200, quantity: 500,
      plate: { name: 'PVC 3mm', width: 600, height: 1200 },
      platesCount: null, itemsPerPlate: null,
      isRectoVerso: false, rectoVersoType: null,
      hasVarnish: false, hasFlatColor: false, hasImpression: true,
      inkMlPerPlate: 22, cuttingTimePerPoseSeconds: 12,
      amalgameGroupIndex: 0, countPerPlateInGroup: 20,
    },
    {
      id: 4, productTypeName: 'Chevalet de sol',
      flatWidth: 500, flatHeight: 700, quantity: 200,
      plate: { name: 'PVC 5mm', width: 600, height: 800 },
      platesCount: 200, itemsPerPlate: 1,
      isRectoVerso: false, rectoVersoType: null,
      hasVarnish: false, hasFlatColor: false, hasImpression: false,
      inkMlPerPlate: 0, cuttingTimePerPoseSeconds: 20,
      amalgameGroupIndex: null, countPerPlateInGroup: 1,
    },
  ],
}

export const SAMPLE_PS = {
  prodCuttingTimePerPoseSeconds: 12,
  prodAssemblyTimePerPieceSeconds: 45,
  prodPackTimePerPieceSeconds: 30,
  prodMachineTimeMinOverride: 47.25,
  prodInkMlPerPlate: 22,
  prodPlatesCount: 63,
  prodTransportCost: 145,
  prodTransportNotes: 'Livraison mardi matin',
  nbCollages: 3,
  collagePerPLV: 2.40,
  faconnageNotes: 'Colle néoprène — laisser sécher 24h avant emballage',
  conditionnementType: 'kit_unitaire',
  conditionnementNotes: 'Pochette individuelle + intercalaire carton',
  achatsNotes: 'Pieds chromés : commander avant le 15/05',
  remarques: 'Attention fragilité PLV — manipuler avec soin',
  planImageUrl: null,
  status: 'en_cours' as const,
  packagingBoxLengthMm: 460,
  packagingBoxWidthMm: 120,
  packagingBoxHeightMm: 95,
  packagingSupplierRef: null,
  packagingNotes: null,
  prodPackagingUnitPrice: 3.20,
  prodPackagingQuantity: 250,
  prodPackagingMaterial: 'BC',
  delaiRealisation: '5 jours ouvrables',
}
